---
- hosts: Computer-Networks          
  become: yes
  tasks:  
    - name: Install Software for Computer Networks Lab
      apt:
        pkg: "{{ item }}"
        state: present
      with_items:
        - scapy
        - iptables
        - wireshark
        - ebtables
        - ufw
        - nmap
        - quagga
        - ftp
        - isc-dhcp-server
        - ntp
        - iperf
        - iperf3
        - echoping
        - tftp
        - telnet
        - mate-desktop-environment-extras 
        - mate-themes
        - lightdm 
        - lightdm-gtk-greeter 
        - ubuntu-artwork 
        - update-manager

    #- name: Install snort and fwsnort
    #  shell: "{{ item }}" 
    #  with_items:
    #    - DEBIAN_FRONTEND=noninteractive apt-get install -y openssh-server ethtool build-essential libpcap-dev libpcre3-dev libdumbnet-dev bison flex zlib1g-dev liblzma-dev openssl libssl-dev snort fwsnort

    - name: Copy Configuration files
      copy:
        src: /home/abhishek/ansible/ComputerNetworks/CN_R1/configuration-files/
        dest: /etc/


    - name: Copy Lightdm Configuration files
      copy:
        src: /home/abhishek/ansible/ComputerNetworks/CN_R1/lightdm/
        dest: /etc/lightdm/

    - name: Disable lightdm
      shell: systemctl disable lightdm.service
