---
- name: Download source
  git:
    repo: "https://github.com/xen-project/xen.git"
    dest: "{{ xen.location }}" 
    version: stable-4.11  

- name: Run ./configure, make world and make install
  become_user: "{{ xen.user }}" 
  block:
    - shell: ./configure --enable-systemd --with-xenstored=xenstored --libdir=/usr/lib
      args:
        chdir: /home/abhishek/xen
      
    - name: make dist
      make:
        chdir: "{{ xen.location }}" 
        target: dist
      
    - name: make tools
      make:
        chdir: "{{ xen.location }}" 
        target: tools

    - name: make install-xen
      make:
        chdir: "{{ xen.location }}" 
        target: install-xen

    - name: make install-tools
      make:
        chdir: "{{ xen.location }}" 
        target: install-tools 
        params:
          PYTHON_PREFIX_ARG: ""

    - command: "{{ item }}"
      with_items:
        - update-rc.d xencommons defaults 19 18
        - update-rc.d xendomains defaults 21 20
        - update-rc.d xen-watchdog defaults 22 23

    - shell: update-grub 

    - shell: /sbin/ldconfig

    - copy:
        src: xen.cfg
        dest: etc/default/grub.d/

      notify:
        - xen-qemu-dom0-disk-backend
        - xen-init-dom0
        - xenconsoled
        - xendomains
        - xen-watchdog
        - xen-commons
  become: true
